## Задание на повторение материала

### 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np
a = np.linspace(12,23,12)

In [2]:
a

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

### 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
x1 = a.reshape(6,2)
x1

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

In [4]:
x4 = a.reshape(2,6)
x4

array([[12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [5]:
x2 = a.reshape(4,3)
x2

array([[12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [6]:
x3 = a.reshape(3,4)
x3

array([[12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

In [7]:
x5 = a.reshape(12,1)
x5

array([[12.],
       [13.],
       [14.],
       [15.],
       [16.],
       [17.],
       [18.],
       [19.],
       [20.],
       [21.],
       [22.],
       [23.]])

### 3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [8]:
b2 = a.reshape(2,-1)
b2

array([[12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.]])

In [9]:
b3 = a.reshape(3,-1)
b3

array([[12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

In [10]:
b4 = a.reshape(4,-1)
b4

array([[12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [11]:
c2 = a.reshape(-1,2)
c2

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

In [12]:
c3 = a.reshape(-1,4)
c3

array([[12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

### 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


Нет, нельзя!

### 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [13]:
f = np.random.normal(0,1.0,(3,4))
f

array([[ 0.24014713, -0.13877075, -0.18343971,  0.84117427],
       [ 0.16784273, -0.88867726,  0.69577554, -1.71038321],
       [ 0.43400752, -1.76698523,  0.05680882, -0.4806468 ]])

In [14]:
f.reshape(1,12)

array([[ 0.24014713, -0.13877075, -0.18343971,  0.84117427,  0.16784273,
        -0.88867726,  0.69577554, -1.71038321,  0.43400752, -1.76698523,
         0.05680882, -0.4806468 ]])

### 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.


In [15]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### 7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?


In [16]:
d = np.arange(20,1,-2)
b = np.reshape(d,(1,10))
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [17]:
a.shape

(10,)

In [18]:
b.shape

(1, 10)

Разница в количестве строк и столбцов, а так же в размерности массивов.

### 8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [19]:
a = np.zeros((2,2),int)
a

array([[0, 0],
       [0, 0]])

In [20]:
b = np.ones((3,2),int)
b

array([[1, 1],
       [1, 1],
       [1, 1]])

In [21]:
v = np.concatenate([a,b])
v.size

10

### 9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [22]:
a = np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
A = a.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [25]:
B = np.dot(A,At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [26]:
B.shape

(4, 4)

In [27]:
np.linalg.det(B)

0.0

Обратную матрицу для мартицы "B" вычислить невозможно, т.к. ее определитель равен 0.

### 10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.


In [28]:
import random
random.seed(42)
random.randint(0,1000)

654

### 11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 


In [29]:
c = np.random.randint(0,16,size=16)
c

array([10,  0, 12, 10,  3,  9,  8,  3, 15, 15,  5,  4,  9, 10,  8,  9])

### 12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [30]:
C = c.reshape(4,4)
C

array([[10,  0, 12, 10],
       [ 3,  9,  8,  3],
       [15, 15,  5,  4],
       [ 9, 10,  8,  9]])

In [31]:
D = B + (C*10)
D

array([[105,  14, 143, 132],
       [ 44, 140, 166, 152],
       [173, 236, 199, 252],
       [122, 222, 292, 392]])

In [32]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00524353, -0.00589779,  0.00682387, -0.00386556],
       [-0.00611083,  0.00425767,  0.004279  , -0.00234399],
       [ 0.00657164,  0.01422885, -0.00394418, -0.00519467],
       [-0.00306639, -0.01117473, -0.00160906,  0.00895103]])

In [33]:
np.linalg.det(D)

-322561600.0000004

In [34]:
np.linalg.matrix_rank(D)

4

### 13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [35]:
D_inv[D_inv<0] = 0
D_inv[D_inv>0] = 1
D_inv

array([[1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.]])

In [36]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [37]:
C

array([[10,  0, 12, 10],
       [ 3,  9,  8,  3],
       [15, 15,  5,  4],
       [ 9, 10,  8,  9]])

In [41]:
E = np.where(D_inv<1,C,B)
E

array([[  5,   0,  23,  10],
       [  3,  50,  86,   3],
       [ 23,  86,   5,   4],
       [  9,  10,   8, 302]])